# BUDDY iOS Project Configuration

platform :ios, '15.0'

target 'BuddyVoice' do
  use_frameworks!

  # Voice Processing
  pod 'PvPorcupine', '~> 3.0'      # Wake word detection
  pod 'Vosk', '~> 0.3'             # Speech recognition
  
  # Audio & Media
  pod 'AVFoundation'
  
  # Networking
  pod 'Alamofire', '~> 5.6'        # HTTP networking
  
  # Reactive Programming
  pod 'Combine'
  
  # Utilities
  pod 'SwiftUI'
  pod 'Foundation'
  
  target 'BuddyVoiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuddyVoiceUITests' do
    # Pods for UI testing
  end
end

# watchOS Target
target 'BuddyVoice-watchOS' do
  platform :watchos, '8.0'
  use_frameworks!
  
  # Simplified dependencies for watchOS
  pod 'PvPorcupine', '~> 3.0'
  pod 'Foundation'
  pod 'WatchKit'
  
  target 'BuddyVoice-watchOSTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '8.0'
      
      # Enable bitcode for all targets
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      
      # Optimize for voice processing
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
    end
  end
end
